/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export default class MediaConstants {
  /**
   * 返回键
   * Back button.
   */
  static readonly TITLE_BAR_BACK: Resource = $r('app.media.ic_public_back')

  /**
   * 主页图标黑
   * Homepage icon black.
   */
  static readonly BOTTOM_TAB_HOMEPAGE_BLACK: Resource = $r('app.media.ic_tab_homepage_black');

  /**
   * 主页图标白
   * Homepage icon white.
   */
  static readonly BOTTOM_TAB_HOMEPAGE_WHITE: Resource = $r('app.media.ic_tab_homepage_white');

  /**
   * 主页图标灰
   * Homepage icon grey.
   */
  static readonly BOTTOM_TAB_HOMEPAGE_GREY: Resource = $r('app.media.ic_tab_homepage_grey');

  /**
   * 日历图标黑
   * Calendar icon black.
   */
  static readonly BOTTOM_TAB_CALENDAR_BLACK: Resource = $r('app.media.ic_tab_calendar_black');

  /**
   * 日历图标白
   * Calendar icon white.
   */
  static readonly BOTTOM_TAB_CALENDAR_WHITE: Resource = $r('app.media.ic_tab_calendar_white');

  /**
   * 日历图标灰
   * Calendar icon grey.
   */
  static readonly BOTTOM_TAB_CALENDAR_GREY: Resource = $r('app.media.ic_tab_calendar_grey');

  /**
   * 统计图标黑
   * Summary icon black.
   */
  static readonly BOTTOM_TAB_SUMMARY_BLACK: Resource = $r('app.media.ic_tab_summary_black');

  /**
   * 统计图标白
   * Summary icon white.
   */
  static readonly BOTTOM_TAB_SUMMARY_WHITE: Resource = $r('app.media.ic_tab_summary_white');

  /**
   * 统计图标灰
   * Summary icon grey.
   */
  static readonly BOTTOM_TAB_SUMMARY_GREY: Resource = $r('app.media.ic_tab_summary_grey');

  /**
   * 设置图标黑
   * Setting icon black.
   */
  static readonly BOTTOM_TAB_SETTING_BLACK: Resource = $r('app.media.ic_tab_setting_black');

  /**
   * 设置图标白
   * Setting icon white.
   */
  static readonly BOTTOM_TAB_SETTING_WHITE: Resource = $r('app.media.ic_tab_setting_white');

  /**
   * 设置图标灰
   * Setting icon grey.
   */
  static readonly BOTTOM_TAB_SETTING_GREY: Resource = $r('app.media.ic_tab_setting_grey');
}