/**
 * Common constants for all features.
 */
export default class CommonConstants {
  /*
   * 布尔值是
   * Boolean True.
   */
  static readonly BOOLEAN_TRUE: boolean = true;
  /*
   * 布尔值否
   * Boolean False.
   */
  static readonly BOOLEAN_FALSE: boolean = false;
  /*
   * 相对布局下依赖父容器
   * Relate parent container in relative layout.
   */
  static readonly RELATIVE_CONTAINER: string = '__container__';
  /*
   * 加载页跳转延迟
   * Delay from splashpage to mainpage.
   */
  static readonly SPLASHPAGE_ROUTER_DELAY: number = 2000;
}