/**
 * Style constants for all features.
 */
export default class StyleConstants {
  /*
   * 满宽度
   * Full width.
   */
  static readonly FULL_WIDTH = '100%';
  /*
   * 满高度
   * Full height.
   */
  static readonly FULL_HEIGHT = '100%';
  /*
   * 半宽度
   * Half width.
   */
  static readonly HALF_WIDTH = '50%';
  /*
   * 半高度
   * Half height.
   */
  static readonly HALF_HEIGHT = '50%';
  /*
   * 加载页Logo底边距
   * Splash page logo bottom margin.
   */
  static readonly SPLASHPAGE_LOGO_MARGIN_BOTTOM = '27.5%';
  /*
   * 主页侧边栏宽度
   * Side tab width.
   */
  static readonly SIDETAB_WIDTH = '18%';
  /*
   * 主页侧边栏内按钮底边距
   * Side tab icon bottom margin.
   */
  static readonly TABITEMBUILDER_MARGIN_BOTTOM = '20vp';
}